@baseUrl = http://localhost:3050/api/v1

### Preparacion - Plantilla compatible
# @name template
POST {{baseUrl}}/templates
X-API-Key: {{$dotenv SERVICE_API_KEY}}
Content-Type: application/json

{ "nombre": "tc13-template-{{$timestamp}}", "canal": "EMAIL", "contenido": "Hola", "variables": [] }

### TC-13.1 - Header omitido
POST {{baseUrl}}/notifications
X-API-Key: {{$dotenv SERVICE_API_KEY}}
Content-Type: application/json

{ "canal": "EMAIL", "destinatario": "cliente@example.com", "plantillaId": {{template.response.body.$.id}}, "variables": {} }


### TC-13.2 - Header solo con espacios sin idempotencia
POST {{baseUrl}}/notifications
X-API-Key: {{$dotenv SERVICE_API_KEY}}
Idempotency-Key:    
Content-Type: application/json

{ "canal": "EMAIL", "destinatario": "cliente@example.com", "plantillaId": {{template.response.body.$.id}}, "variables": {} }


### TC-13.3 - Header mayor a 128 caracteres
POST {{baseUrl}}/notifications
X-API-Key: {{$dotenv SERVICE_API_KEY}}
Idempotency-Key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Content-Type: application/json

{ "canal": "EMAIL", "destinatario": "cliente@example.com", "plantillaId": {{template.response.body.$.id}}, "variables": {} }
